import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'en' | 'si';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const dictionary: Record<string, Record<string, string>> = {
  si: {
    // Sidebar / Navigation
    "Dashboard": "දළ විශ්ලේෂණය",
    "Collections": "එකතු කිරීම්",
    "Financials": "මූල්‍ය විස්තර",
    "Inventory": "තොග කළමනාකරණය",
    "Requests & Approvals": "ඉල්ලීම් සහ අනුමැතිය",
    "Transport Tracking": "ට්රාන්ස්පෝර්ට් ලුහුබැඳීම",
    "Quality Assessment": "තත්ත්ව පරීක්ෂාව",
    "TRI Circulars": "TRI චක්‍රලේඛ",
    "Reports": "වාර්තා",
    "User Management": "පරිශීලක කළමනාකරණය",
    "Route Management": "මාර්ග කළමනාකරණය",
    "Collection Route Management": "එකතු කිරීමේ මාර්ග කළමනාකරණය",
    "Total Estate Routes": "මුළු වතු මාර්ග ගණන",
    "Unique Area Codes": "අනන්‍ය ප්‍රදේශ කේත",
    "Define Collection Route": "එකතු කිරීමේ මාර්ගය ඇතුල් කරන්න",
    "Route Division Name": "මාර්ගයේ නම",
    "Route Prefix Code": "මාර්ගයේ කේතය",
    "Add Route": "මාර්ගයක් එක් කරන්න",
    "Settings": "සැකසුම්",
    "Sign Out": "පිටවන්න",
    "Manager": "කළමනාකරු",
    "Extension Officer": "ව්‍යාප්ති නිලධාරී",
    "Office Staff": "කාර්යාල කාර්ය මණ්ඩලය",
    "Store Keeper": "ස්ටොර් කීපර්",
    "Factory Staff": "ෆැක්ටරි ස්ටාෆ්",
    "Staff": "සේවක",

    // Dashboard
    "Project Dalupotha": "දළුපොත ව්‍යාපෘතිය",
    "TODAY": "අද",
    "WEEK": "සතිය",
    "MONTH": "මාසය",
    "CUSTOM": "වෙනත්",
    "Operational Overview": "මෙහෙයුම් දළ විශ්ලේෂණය",
    "TODAY'S GREEN LEAF": "අද දින අමු තේ දළු",
    "PENDING SYNC": "සමමුහුර්ත වීමට ඇති",
    "ROUTE PROGRESS": "මාර්ග ප්‍රගතිය",
    "SUPPLIERS ACTIVE": "සක්‍රීය සැපයුම්කරුවන්",
    "RECORDS IN QUEUE": "පෝලිමේ ඇති වාර්තා",
    "COMPLETE": "සම්පූර්ණයි",
    "LIVE SYSTEM ACTIVE": "පද්ධතිය සක්‍රීයයි",
    "Action Required": "අවධානය යොමු කරන්න",
    "Pending Requests": "පොරොත්තු ඉල්ලීම්",
    "Advances and Fertilizer orders are waiting for your final approval.": "අත්තිකාරම් සහ පොහොර ඇණවුම් ඔබේ අවසාන අනුමැතිය සඳහා රැඳී පවතී.",
    "GO TO APPROVALS": "අනුමැතිය සඳහා යන්න",
    "YIELD ANALYSIS": "අස්වැන්න විශ්ලේෂණය",
    "AGENT PERFORMANCE": "නියෝජිත කාර්යසාධනය",
    "VIEW ALL": "සියල්ල බලන්න",
    "kg": "kg",
    "kg collected": "එකතු කළ බර",
    "Awaiting sync": "සමමුහුර්ත වන තෙක්",
    "records in queue": "වාර්තා පෝලිමේ ඇත",
    "suppliers active": "සක්‍රීය සැපයුම්කරුවන්",
    "complete": "සම්පූර්ණයි",
    "Generating visualization...": "දත්ත විශ්ලේෂණය කරමින් පවතී...",
    "LAST 7 DAYS": "පසුගිය දින 7",
    "April": "අප්‍රේල්",
    "Action Required": "අවධානය යොමු කරන්න",
    "Pending Requests": "පොරොත්තු ඉල්ලීම්",
    "Go to Approvals": "අනුමැතිය සඳහා යන්න",
    "Notifications": "දැනුම්දීම්",
    "Mark all read": "සියල්ල කියවූ ලෙස ලකුණු කරන්න",
    "No notifications yet": "තවමත් දැනුම්දීම් නොමැත",
    "My Profile": "මගේ ගිණුම",
    "Account Settings": "ගිණුම් සැකසුම්",
    "Today": "අද",
    "Week": "සතිය",
    "Month": "මාසය",
    "Custom": "වෙනත්",
    "just now": "දැන්",
    "m ago": "මිනිත්තු කිහිපයකට පෙර",
    "h ago": "පැය කිහිපයකට පෙර",
    "d ago": "දින කිහිපයකට පෙර",
    "item": "අයිතමය",
    "pending service request": "පොරොත්තු සේවා ඉල්ලීම",
    "s": "",
    "s ready for dispatch": "බෙදා හැරීම සඳහා සූදානම්",
    " ready for dispatch": "බෙදා හැරීම සඳහා සූදානම්",
    "that need review.": "සලකා බැලිය යුතු",
    "Dismiss all request alerts": "සියලු ඉල්ලීම් දැනුම්දීම් ඉවත් කරන්න",
    "Process Now": "දැන් ක්‍රියාත්මක කරන්න",
    "Snooze this alert": "මෙම දැනුම්දීම පසුවට තබන්න",

    // Settings
    "System Settings": "පද්ධති සැකසුම්",
    "Global configuration and external service integrations": "පද්ධති සැකසුම් සහ බාහිර සේවා සම්බන්ධතා",
    "System": "පද්ධතිය",
    "Integration": "සම්බන්ධතා",
    "Language Preference": "භාෂාව තෝරන්න",
    "Choose your preferred interface language": "ඔබ කැමති භාෂාව තෝරාගන්න",
    "Sinhala": "සිංහල",
    "English": "ඉංග්‍රීසි",
    "Edit": "සංස්කරණය",
    "Edit All": "සියල්ල සංස්කරණය කරන්න",
    "Factory Name": "කර්මාන්තශාලාවේ නම",
    "Financial Year Start": "මූල්‍ය වර්ෂයේ ආරම්භය",
    "Advance Limit (Rs.)": "අත්තිකාරම් සීමාව (රු.)",
    "Debt Alert Threshold": "ණය අනතුරු ඇඟවීමේ සීමාව",
    "Estate & Manager Profile": "වත්ත සහ කළමනාකරු පැතිකඩ",
    "General Information": "සාමාන්‍ය තොරතුරු",
    "Manage identity & credentials": "හැඳුනුම්පත සහ අක්තපත්‍ර කළමනාකරණය කරන්න",
    "Estate Details": "වතු විස්තර",
    "Estate Name": "වතුයායේ නම",
    "Phone": "දුරකථන අංකය",
    "Address": "ලිපිනය",
    "Manager Account": "කළමනාකරු ගිණුම",
    "Manager Name": "කළමනාකරුගේ නම",
    "Email": "විද්‍යුත් තැපෑල",
    "Password": "මුරපදය",
    "Save All Changes": "සියලු වෙනස්කම් සුරකින්න",
    "Select your language": "ඔබේ භාෂාව තෝරන්න",
    "Current": "වත්මන්",
    "Leaf Pricing": "දළු මිල ගණන්",
    "Current Rate": "වත්මන් අනුපාතය",
    "Since": "සිට",
    "Advance Limit": "අත්තිකාරම් සීමාව",
    "Max Request": "උපරිම ඉල්ලීම",
    "Security": "ආරක්ෂාව",
    "System Locked": "පද්ධතිය අගුළු දමා ඇත",
    "Access to security auditing is restricted to root admins.": "ආරක්ෂක විගණනයට ප්‍රවේශය ප්‍රධාන පරිපාලකයින්ට පමණක් සීමා වේ.",
    "Root Admin Only": "ප්‍රධාන පරිපාලක පමණි",
    "Advanced Security Controls": "උසස් ආරක්ෂක පාලනයන්",
    "Update Leaf Rate?": "දළු අනුපාතය යාවත්කාලීන කරන්නද?",
    "This change will immediately affect all supplier earnings calculations.": "මෙම වෙනස සියලුම සැපයුම්කරුවන්ගේ ඉපැයීම් ගණනය කිරීම් කෙරෙහි වහාම බලපානු ඇත.",
    "Update Advance Limit?": "අත්තිකාරම් සීමාව යාවත්කාලීන කරන්නද?",
    "Requests above this amount will be automatically rejected.": "මෙම ප්‍රමාණයට වඩා වැඩි ඉල්ලීම් ස්වයංක්‍රීයව ප්‍රතික්ෂේප කරනු ලැබේ.",
    "Confirm": "තහවුරු කරන්න",
    "Cancel": "අවලංගු කරන්න",
    "Update": "යාවත්කාලීන කරන්න",

    // Common
    "Attention Needed": "අවධානය යොමු කරන්න",
    "You have": "ඔබට",
    "pending service requests that need review.": "සලකා බැලිය යුතු සේවා ඉල්ලීම් පවතී.",
    "Review All": "සියල්ල බලන්න",
    "Last sync": "අවසාන සමමුහුර්තකරණය",
    "All Types": "සියලුම වර්ග",
    "Advance": "අත්තිකාරම්",
    "Fertilizer": "පොහොර",
    "Transport": "ට්රාන්ස්පෝර්ට්",
    "Machine Rent": "යන්ත්‍රෝපකරණ කුලියට ගැනීම",
    "Tool Purchase": "මෙවලම් මිලදී ගැනීම",
    "Tools": "මෙවලම්",
    "Advisory": "උපදෙස්",
    "Leaf Bags": "දළු මලු",
    "Ready to Dispatch": "බෙදා හැරීම සඳහා සූදානම්",
    "Pending": "පොරොත්තු",
    "Approved Today": "අද අනුමත කරන ලද",
    "Rejected Today": "අද ප්‍රතික්ෂේප කරන ලද",
    "Dispatched Today": "අද බෙදා හරින ලද",
    "Export List": "ලැයිස්තුව අපනයනය කරන්න",
    "Pending Approvals": "අනුමැතිය සඳහා ඇති ඉල්ලීම්",
    "Recently Approved": "මෑතකදී අනුමත කරන ලද",
    "Recently Rejected": "මෑතකදී ප්‍රතික්ෂේප කරන ලද",
    "Dispatched": "බෙදා හරින ලද",
    "Search by name or ID...": "නම හෝ හැඳුනුම්පත මගින් සොයන්න...",
    "View": "බලන්න",
    "Approve": "අනුමත කරන්න",
    "Reject": "ප්‍රතික්ෂේප කරන්න",
    "Dispatch": "බෙදා හරින්න",
    "Request Detail": "ඉල්ලීම් විස්තර",
    "Supplier Info": "සැපයුම්කරුගේ විස්තර",
    "Financial Standing": "මූල්‍ය තත්ත්වය",
    "Outstanding Debt": "හිඟ ණය",
    "Supply This Month": "මෙම මාසයේ සැපයුම",
    "Debt/Supply Ratio": "ණය/සැපයුම් අනුපාතය",
    "Decision Status": "තීරණ තත්ත්වය",
    "Decision": "තීරණය",
    "Manager Remark": "කළමනාකරුගේ සටහන",
    "Manager Remarks": "කළමනාකරුගේ සටහන්",
    "Final Deduction (Rs.)": "අවසාන අඩු කිරීම් (රු.)",
    "Reject Request": "ප්‍රතික්ෂේප කරන්න",
    "Approve Request": "අනුමත කරන්න",
    "Confirm Dispatch": "බෙදා හැරීම තහවුරු කරන්න",
    "Close": "වසා දමන්න",
    "Supplier": "සැපයුම්කරු",
    "Passbook ID": "පාස්බුක් නම්බර්",
    "Request Type": "ඉල්ලීම් වර්ගය",
    "Amount / Qty": "ප්‍රමාණය",
    "Date": "දිනය",
    "Assigned Agent": "පත් කළ නියෝජිතයා",
    "Request ID": "ඉල්ලීම් අංකය",
    "Status": "තත්ත්වය",
    "Actions": "ක්‍රියාමාර්ග",
    "Available": "තිබෙන ප්‍රමාණය",
    "units": "ඒකක",
    "bags": "මලු",
    "days": "දින",
    "Soil query": "පස පිළිබඳ ගැටළු",
    "Provision": "සැපයීම",
    "Standard Transport": "සාමාන්‍ය ට්රාන්ස්පෝර්ට්",
    "Service Category": "සේවා වර්ගය",
    "Logistic": "ට්රාන්ස්පෝර්ට්",
    "Transport Fee (Rs.)": "ට්රාන්ස්පෝර්ට් ගාස්තුව (රු.)",
    "Rental Configuration": "කුලියට දීමේ සැකසුම්",
    "Duration": "කාලසීමාව",
    "Total Rental Fee (Rs.)": "මුළු කුලී ගාස්තුව (රු.)",
    "Inventory Pricing": "තොග මිල ගණන්",
    "Calculated Total": "ගණනය කළ මුළු මුදල",
    "Source": "මූලාශ්‍රය",
    "Direct": "සෘජු",
    "Agent": "නියෝජිතයා",
    "Passbook": "පාස්බුක් නම්බර්",
    "Emp ID": "සේවක අංකය",
    "Requested At": "ඉල්ලුම් කළ වේලාව",
    "Supplier Note": "සැපයුම්කරුගේ සටහන",
    "Agent Note": "නියෝජිතයාගේ සටහන",
    "Rejected At": "ප්‍රතික්ෂේප කළ වේලාව",
    "Approved At": "අනුමත කළ වේලාව",
    "APPROVED": "අනුමතයි",
    "APPROVED BY MGR": "කළමනාකරු විසින් අනුමත කරන ලදි",
    "REJECTED": "ප්‍රතික්ෂේපිතයි",
    "DISPATCHED": "බෙදා හරින ලදී",
    "Send Advice": "උපදෙස් යවන්න",
    "Approve & Send to Store Keeper": "අනුමත කර ස්ටොර් කීපර් වෙත යවන්න",
    "Dismiss Request": "ඉවත් කරන්න",
    "Today": "අද",
    "This Week": "මෙම සතිය",
    "This Month": "මෙම මාසය",
    "Search by supplier, ID or TA...": "සැපයුම්කරු, හැඳුනුම්පත හෝ ට්රාන්ස්පෝර්ට් නියෝජිතයා මගින් සොයන්න...",
    "Export": "අපනයනය",
    "COLLECTION ID": "එකතු කිරීමේ හැඳුනුම්පත",
    "SUPPLIER": "සැපයුම්කරු",
    "WEIGHT (KG)": "බර (kg)",
    "NET (KG)": "ශුද්ධ බර (kg)",
    "TRANSPORT AGENT": "ට්රාන්ස්පෝර්ට් නියෝජිතයා",
    "Collection Route": "එකතු කිරීමේ මාර්ගය",
    "Select Collection Route": "මාර්ගය තෝරන්න",
    "GPS": "GPS",
    "TIME": "වේලාව",
    "SYNC": "සමමුහුර්ත කිරීම",
    "Loading Registry...": "ලියාපදිංචි දත්ත පූරණය වෙමින් පවතී...",
    "Unknown": "නොදනී",
    "Detail": "විස්තර",
    "Collection Details": "එකතු කිරීමේ විස්තර",
    "Processed By": "සකසන ලද්දේ",
    "Factory Staff": "ෆැක්ටරි ස්ටාෆ්",
    "Not yet processed by factory staff": "කර්මාන්තශාලා කාර්ය මණ්ඩලය විසින් තවමත් සකසා නැත",
    "Gross Weight": "මුළු බර",
    "Net Weight": "ශුද්ධ බර",
    "Collected at": "එකතු කළ වේලාව",
    "GPS Verified": "GPS තහවුරු කරන ලදී",
    "Manual Entry": "අතින් ඇතුළත් කරන ලදී",
    "Download Receipt": "රසීදය බාගත කරන්න",
    "unit": "ඒකකය",
    "Yes": "ඔව්",
    "No": "නැත",
    "All": "සියල්ල",
    "TOTAL FERTILIZER STOCK": "පොහොර මුළු තොගය",
    "TOTAL LEAF BAGS": "දළු මලු මුළු සංඛ්‍යාව",
    "LOW STOCK ALERTS": "අඩු තොග අනතුරු ඇඟවීම්",
    "TOOLS UNITS": "මෙවලම් ඒකක",
    "Reorder Now": "දැන් නැවත ඇණවුම් කරන්න",
    "Inventory Items": "තොග අයිතම",
    "Add Item": "අයිතමයක් එක් කරන්න",
    "Search item...": "අයිතමය සොයන්න...",
    "ITEM": "අයිතමය",
    "CATEGORY": "ප්‍රභේදය",
    "STOCK": "තොගය",
    "RESERVED": "වෙන් කර ඇත",
    "REORDER LEVEL": "නැවත ඇණවුම් මට්ටම",
    "STOCK LEVEL": "තොග මට්ටම",
    "UNIT COST": "ඒකක පිරිවැය",
    "STATUS": "තත්ත්වය",
    "ACTIONS": "ක්‍රියාමාර්ග",
    "History": "ඉතිහාසය",
    "Update": "යාවත්කාලීන කරන්න",
    "Update Stock": "තොගය යාවත්කාලීන කරන්න",
    "SELECTED ITEM": "තෝරාගත් අයිතමය",
    "New Stock": "නව තොගය",
    "Saving...": "සුරකිමින් පවතී...",
    "Save Changes": "වෙනස්කම් සුරකින්න",
    "Low Stock": "අඩු තොග",
    "OK": "හරි",
    "kg": "kg",
    "bags": "මලු",
    "units": "ඒකක",
    "All Categories": "සියලුම ප්‍රභේද",
    "Fertilizer": "පොහොර",
    "Bags": "මලු",
    "Tools": "මෙවලම්",
    "available": "ලබාගත හැකිය",
    "reserved": "වෙන් කර ඇත",
    "Financial Treasury": "මුල්‍ය භාණ්ඩාගාරය",
    "Manage supplier payouts, advances, and ledger reconciliation": "සැපයුම්කරුවන්ගේ ගෙවීම්, අත්තිකාරම් සහ ලෙජර් සැසඳුම් කළමනාකරණය කරන්න",
    "Leaf Price: Rs.": "දළු මිල: රු. ",
    "Sync Ledgers": "ලෙජර් සමමුහුර්ත කරන්න",
    "Syncing...": "සමමුහුර්ත වෙමින් පවතී...",
    "Overview": "දළ විශ්ලේෂණය",
    "Payout Generator": "ගෙවීම් උත්පාදනය",
    "Supplier Ledgers": "සැපයුම්කරු ලෙජර්",
    "Treasury Settings": "භාණ්ඩාගාර සැකසුම්",
    "Projected Payout": "අපේක්ෂිත ගෙවීම",
    "Unpaid net weight total": "නොගෙවූ මුළු ශුද්ධ බර",
    "Paid (Current Month)": "ගෙවන ලද (වත්මන් මාසය)",
    "18 transactions completed": "ගනුදෙනු 18 ක් අවසන්",
    "Active Advances": "සක්‍රීය අත්තිකාරම්",
    "Awaiting deduction": "අඩු කිරීමට නියමිතයි",
    "Debt Recovery": "ණය අයකර ගැනීම",
    "Outstanding store credits": "නොපියවූ ගබඩා බැර",
    "Recent Transactions": "මෑතකාලීන ගනුදෙනු",
    "Cash flow reconciliation": "මුදල් ප්‍රවාහ සැසඳුම",
    "View All": "සියල්ල බලන්න",
    "Treasury Snapshot": "භාණ්ඩාගාර තත්ත්වය",
    "Available cash reserves for supplier settlements this cycle.": "මෙම වටයේ සැපයුම්කරුවන්ගේ පියවීම් සඳහා පවතින මුදල් සංචිත.",
    "Monthly Target": "මාසික ඉලක්කය",
    "Generate Balance Sheet": "ශේෂ පත්‍රය උත්පාදනය කරන්න",
    "Mass Payout Generator": "සමූහ ගෙවීම් උත්පාදක යන්ත්‍රය",
    "Process earnings for all suppliers in a specific cycle": "නිශ්චිත වටයක සියලුම සැපයුම්කරුවන්ගේ ඉපැයීම් සකසන්න",
    "Run Calculations": "ගණනය කිරීම් සිදු කරන්න",
    "Processing...": "සකසමින් පවතී...",
    "Supplier": "සැපයුම්කරු",
    "Net Weight": "ශුද්ධ බර",
    "Gross Earnings": "මුළු ඉපැයීම්",
    "Advances": "අත්තිකාරම්",
    "Final Payout": "අවසාන ගෙවීම",
    "Action": "ක්‍රියාව",
    "Search supplier by name or passbook...": "සැපයුම්කරු නම හෝ පාස්බුක් නම්බර් මගින් සොයන්න...",
    "Filters": "පෙරහන්",
    "Treasury Configuration": "භාණ්ඩාගාර වින්‍යාසය",
    "Global parameters for financial calculations": "මූල්‍ය ගණනය කිරීම් සඳහා ගෝලීය පරාමිතීන්",
    "Current Green Leaf Price (Rs/kg)": "වත්මන් අමු දළු මිල (රු/kg)",
    "This price will be used for all projected earnings and payout calculations.": "මෙම මිල සියලුම අපේක්ෂිත ඉපැයීම් සහ ගෙවීම් ගණනය කිරීම් සඳහා භාවිතා කරනු ලැබේ.",
    "Balance Owed": "ගෙවිය යුතු ශේෂය",
    "Payout": "ගෙවීම",
    "Advance": "අත්තිකාරම්",
    "Debt": "ණය",
    "Completed": "අවසන්",
    "Pending": "ප්‍රමාදිත",
    "Cleared": "පියවා ඇත",
    "Issue": "නිකුත් කරන්න",
    "Yesterday": "ඊයේ",
    "hours ago": "පැය කිහිපයකට පෙර",
    "days ago": "දින කිහිපයකට පෙර",
    "week ago": "සතියකට පෙර",
    "weeks ago": "සති කිහිපයකට පෙර",
    "Reports & Analytics": "වාර්තා සහ විශ්ලේෂණ",
    "System audits and comprehensive data exports": "පද්ධති විගණනයන් සහ විස්තීර්ණ දත්ත අපනයනයන්",
    "Daily Collection Report": "දෛනික එකතු කිරීමේ වාර්තාව",
    "Monthly Financial Report": "මාසික මූල්‍ය වාර්තාව",
    "Inventory Stock Report": "තොග තොග වාර්තාව",
    "TA Performance Report": "ට්රාන්ස්පෝර්ට් නියෝජිත කාර්ය සාධන වාර්තාව",
    "Small Holder Supply Ranking": "කුඩා වතු හිමියන්ගේ සැපයුම් ශ්‍රේණිගත කිරීම",
    "Debt Ageing Report": "ණය කාලීන වාර්තාව",
    "System Audit Log": "පද්ධති විගණන ලොගය",
    "TIME": "වේලාව",
    "USER": "පරිශීලකයා",
    "ACTION": "ක්‍රියාව",
    "TARGET ENTITY": "ඉලක්කගත ඒකකය",
    "STATUS": "තත්ත්වය",
    "View Full Audit Log →": "සම්පූර්ණ විගණන ලොගය බලන්න →",
    "Database": "දත්ත සමුදාය",
    "Cloud Sync": "ක්ලවුඩ් සමමුහුර්තකරණය",
    "Ginum Ledger": "ගිණුම් ලෙජරය",
    "BLE Gateway": "බී.එල්.ඊ. ද්වාරය",
    "PDF": "පී.ඩී.එෆ්",
    "Excel": "එක්සෙල්",
    "Approved Advance": "අනුමත අත්තිකාරම්",
    "Viewed Reports": "වාර්තා බලන ලදි",
    "Automated Sync": "ස්වයංක්‍රීය සමමුහුර්තකරණය",
    "Rejected Request": "ප්‍රතික්ෂේපිත ඉල්ලීම",
    "Success": "සාර්ථකයි",
    "Info": "තොරතුරු",
    "Warning": "අවවාදයයි",
    "Operational Overview": "මෙහෙයුම් දළ විශ්ලේෂණය",
    "LIVE SYSTEM ACTIVE": "පද්ධතිය සක්‍රීයයි",
    "TODAY'S GREEN LEAF": "අද දින අමු දළු",
    "suppliers active": "සැපයුම්කරුවන් සක්‍රීයයි",
    "PENDING SYNC": "සමමුහුර්ත කිරීමට ඉතිරි",
    "records in queue": "වාර්තා පෝලිමේ",
    "ROUTE PROGRESS": "මාර්ග ප්‍රගතිය",
    "complete": "අවසන්",
    "Action Required": "ක්‍රියාමාර්ග අවශ්‍යයි",
    "Pending Requests": "ප්‍රමාදිත ඉල්ලීම්",
    "Advances and Fertilizer orders are waiting for your final approval.": "අත්තිකාරම් සහ පොහොර ඇණවුම් ඔබේ අවසන් අනුමැතිය සඳහා රැඳී පවතී.",
    "Go to Approvals": "අනුමැතිය සඳහා යන්න",
    "YIELD ANALYSIS": "අස්වැන්න විශ්ලේෂණය",
    "LAST 7 DAYS": "පසුගිය දින 7",
    "Generating visualization...": "දෘශ්‍යකරණය උත්පාදනය වෙමින් පවතී...",
    "AGENT PERFORMANCE": "නියෝජිත කාර්ය සාධනය",
    "VIEW ALL": "සියල්ල බලන්න",
    "kg collected": "kg එකතු කරන ලදි",
    "Awaiting sync": "සමමුහුර්තකරණය අපේක්ෂාවෙන්",
    "Transport Live Tracking": "ට්රාන්ස්පෝර්ට් සජීවී ලුහුබැඳීම",
    "Real-time GPS visibility for leaf collection fleet": "දළු එකතු කිරීමේ රථ පෙළ සඳහා තථ්‍ය කාලීන ජීපීඑස් දෘශ්‍යතාව (ට්රාන්ස්පෝර්ට්)",
    "Refetch GPS": "ජීපීඑස් නැවත ලබා ගන්න",
    "Active TAs": "සක්‍රීය ට්රාන්ස්පෝර්ට් නියෝජිතයන්",
    "GPS tracking live": "සජීවී ජීපීඑස් ලුහුබැඳීම",
    "Records not yet synced": "තවමත් සමමුහුර්ත කර නොමැති වාර්තා",
    "Offline TAs": "අක්‍රීය ට්රාන්ස්පෝර්ට් නියෝජිතයන්",
    "No signal detected": "සංඥා කිසිවක් හමු නොවීය",
    "Total Collected Today": "අද දින එකතු කරන ලද මුළු ප්‍රමාණය",
    "Interactive Map: Uva Halpewatte Estate": "අන්තර්ක්‍රියාකාරී සිතියම: ඌව හල්පේවත්ත වත්ත",
    "GPS Engine Ready • 5 Active Nodes Detected": "ජීපීඑස් එන්ජිම සූදානම් • සක්‍රීය නෝඩ් 5 ක් හඳුනාගෙන ඇත",
    "AGENT": "නියෝජිතයා",
    "COLLECTIONS": "එකතු කිරීම්",
    "TOTAL KG": "මුළු kg",
    "LAST SYNC": "අවසන් වරට සමමුහුර්ත කළේ",
    "Route": "මාර්ගය",
    "Active": "සක්‍රීයයි",
    "Offline": "අක්‍රීයයි",
    "User Management": "පරිශීලක කළමනාකරණය",
    "Control system access and role assignments": "පද්ධති ප්‍රවේශය සහ භූමිකාවන් පැවරීම පාලනය කරන්න",
    "All Roles": "සියලුම භූමිකාවන්",
    "Manager": "කළමනාකරු",
    "Extension Officer": "ප්‍රසාරණ නිලධාරී",
    "Office Staff": "කාර්යාල කාර්ය මණ්ඩලය",
    "Factory Staff": "ෆැක්ටරි ස්ටාෆ්",
    "Store Keeper": "ස්ටොර් කීපර්",
    "Transport Agent": "ට්රාන්ස්පෝර්ට් නියෝජිතයා",
    "Supplier": "සැපයුම්කරු",
    "Add User": "පරිශීලකයා එක් කරන්න",
    "USER ID": "පරිශීලක හැඳුනුම්පත",
    "NAME": "නම",
    "ROLE": "භූමිකාව",
    "LAST ACTIVE": "අවසන් වරට සක්‍රීය වූයේ",
    "Loading users...": "පරිශීලකයින් පූරණය වෙමින් පවතී...",
    "No users found.": "පරිශීලකයින් කිසිවෙකු හමු නොවීය.",
    "Profile": "ප්රොෆයිලය",
    "Deactivate": "අක්‍රීය කරන්න",
    "Activate": "සක්‍රීය කරන්න",
    "Select User Role": "පරිශීලක භූමිකාව තෝරන්න",
    "Create System User": "පද්ධති පරිශීලකයා සාදන්න",
    "Create Transport Agent": "ට්රාන්ස්පෝර්ට් නියෝජිතයා සාදන්න",
    "Create Supplier": "සැපයුම්කරු සාදන්න",
    "Please select the role you wish to create:": "කරුණාකර ඔබ සෑදීමට කැමති භූමිකාව තෝරන්න:",
    "Supplier (Small Holder)": "සැපයුම්කරු (කුඩා වතු හිමියා)",
    "Next": "මීළඟ",
    "Full Name": "සම්පූර්ණ නම",
    "Employee ID": "සේවක හැඳුනුම්පත",
    "Username": "පරිශීලක නාමය",
    "Email Address": "විද්‍යුත් තැපැල් ලිපිනය",
    "Contact Number": "සම්බන්ධතා අංකය",
    "NIC Number": "ජාතික හැඳුනුම්පත් අංකය",
    "Date of Birth": "උපන් දිනය",
    "Initial Password": "මූලික මුරපදය",
    "Confirm Password": "මුරපදය තහවුරු කරන්න",
    "Create Staff": "කාර්ය මණ්ඩලය සාදන්න",
    "Agent ID": "නියෝජිත හැඳුනුම්පත",
    "Estate Processing Hub": "වතු සැකසුම් මධ්‍යස්ථානය",
    "Global / Master TA": "ගෝලීය / ප්‍රධාන ට්රාන්ස්පෝර්ට් නියෝජිතයා",
    "Create PIN": "පින් කේතය සාදන්න",
    "Confirm PIN": "පින් කේතය තහවුරු කරන්න",
    "Create TA": "ට්රාන්ස්පෝර්ට් නියෝජිතයා සාදන්න",
    "Passbook No": "පාස්බුක් නම්බර්",
    "Land Name (Optional)": "ඉඩමේ නම (අත්‍යවශ්‍ය නොවේ)",
    "Field In-Charge (TA)": "ක්ෂේත්‍ර භාර නිලධාරී (ට්රාන්ස්පෝර්ට් නියෝජිතයා)",
    "Select Transport Agent...": "ට්රාන්ස්පෝර්ට් නියෝජිතයා තෝරන්න...",
    "Create Login PIN": "ප්‍රවේශ පින් කේතය සාදන්න",
    "Edit Profile": "පැතිකඩ සංස්කරණය කරන්න",
    "Remove User": "පරිශීලකයා ඉවත් කරන්න",
    "Contact Information": "සම්බන්ධතා තොරතුරු",
    "System Metadata": "සිස්ටම් ඩේටා",
    "Current Estate": "වත්මන් වත්ත",
    "Assigned Transport Agent": "පැවරූ ට්රාන්ස්පෝර්ට් නියෝජිතයා",
    "Land Name": "ඉඩමේ නම",
    "Total Arcs": "මුළු අක්කර ප්‍රමාණය",
    "System Settings": "පද්ධති සැකසුම්",
    "Global configuration and external service integrations": "ගෝලීය වින්‍යාසය සහ බාහිර සේවා ඒකාබද්ධ කිරීම්",
    "Language Preference": "භාෂා මනාපය",
    "Choose your preferred interface language": "ඔබේ කැමති අතුරුමුහුණත් භාෂාව තෝරන්න",
    "English": "ඉංග්‍රීසි",
    "Sinhala": "සිංහල",
    "System": "පද්ධතිය",
    "Factory Name": "කර්මාන්තශාලාවේ නම",
    "Financial Year Start": "මූල්‍ය වර්ෂයේ ආරම්භය",
    "April": "අප්‍රේල්",
    "Advance Limit (Rs.)": "අත්තිකාරම් සීමාව (රු.)",
    "Debt Alert Threshold": "ණය අනතුරු ඇඟවීමේ සීමාව",
    "80% of supply value": "සැපයුම් වටිනාකමෙන් 80%",
    "Integration": "ඒකාබද්ධ කිරීම",
    "Every 10 min": "සෑම විනාඩි 10 කට වරක්",
    "Cloud (AWS S3)": "වලාකුළු (AWS S3)",
    "Last Backup": "අවසන් වරට උපස්ථ කළේ",
    "Advanced Security Controls": "උසස් ආරක්ෂක පාලනයන්",
    "Total Arcs": "මුළු අක්කර ප්‍රමාණය",
    "Brought Leaf Register": "ගෙන එන ලද අමු දළු ලේඛනය",
    "Log green leaf weights and apply quality deductions": "අමු දළු බර සටහන් කර ගුණාත්මකභාවය මත අඩු කිරීම් සිදු කරන්න",
    "Refresh": "නැවුම් කරන්න",
    "Processed Today": "අද දින සකසන ලද",
    "Weights logged successfully": "බර සාර්ථකව සටහන් කරන ලදි",
    "Deliveries awaiting processing": "සැකසීම සඳහා රැඳී පවතින බෙදාහැරීම්",
    "Quality-based weight deducted": "ගුණාත්මකභාවය මත පදනම්ව අඩු කළ බර",
    "Gross (kg)": "දළ බර (kg)",
    "Deduction (kg)": "අඩු කිරීම (kg)",
    "Net (kg)": "ශුද්ධ බර (kg)",
    "Action": "ක්‍රියාමාර්ගය",
    "No collections today": "අද දින එකතු කිරීම් නොමැත",
    "Process": "සකසන්න",
    "Quality Assessment": "ගුණාත්මකභාවය ඇගයීම",
    "Process Collection": "එකතු කිරීම සකසන්න",
    "Review weights and apply deductions": "බර පරීක්ෂා කර අඩු කිරීම් සිදු කරන්න",
    "Quality Deduction (kg)": "ගුණාත්මක අඩු කිරීම (kg)",
    "Final Net Weight": "අවසාන ශුද්ධ බර",
    "Confirm Weight": "බර තහවුරු කරන්න",
    "Failed to save deduction. Please try again.": "අඩු කිරීම සුරැකීමට අපොහොසත් විය. කරුණාකර නැවත උත්සාහ කරන්න.",
    "Search by supplier, ID or TA...": "සැපයුම්කරු, හැඳුනුම්පත හෝ ට්රාන්ස්පෝර්ට් නියෝජිතයා අනුව සොයන්න...",
    "All": "සියල්ල",
    "Today": "අද",
    "This Week": "මේ සතියේ",
    "This Month": "මේ මාසයේ",
    "Export": "අපනයනය කරන්න",
    "COLLECTION ID": "එකතු කිරීමේ හැඳුනුම්පත",
    "SUPPLIER": "සැපයුම්කරු",
    "WEIGHT (KG)": "බර (kg)",
    "NET (KG)": "ශුද්ධ බර (kg)",
    "TRANSPORT AGENT": "ට්රාන්ස්පෝර්ට් නියෝජිතයා",
    "TIME": "වේලාව",
    "SYNC": "සමමුහුර්තකරණය",
    "ACTIONS": "ක්‍රියාමාර්ග",
    "Loading Registry...": "ලේඛනය පූරණය වෙමින් පවතී...",
    "Detail": "විස්තර",
    "Collection Details": "එකතු කිරීමේ විස්තර",
    "Collection ID": "එකතු කිරීමේ හැඳුනුම්පත",
    "Processed By": "සකසන ලද්දේ",
    "Factory Staff": "ෆැක්ටරි ස්ටාෆ්",
    "Not yet processed by factory staff": "තවමත් කර්මාන්තශාලා සේවකයින් විසින් සකසා නොමැත",
    "Collected at": "එකතු කළ වේලාව",
    "GPS Verified": "GPS මගින් තහවුරු කර ඇත",
    "Manual Entry": "අතින් ඇතුළත් කරන ලදි",
    "Download Receipt": "ලදුපත බාගන්න",
    "Close": "වසා දමන්න",
    "SYNCED": "සමමුහුර්ත කර ඇත",
    "QUEUED": "පෝලිම් කර ඇත",
    "FAILED": "අසාර්ථක විය",
    "Yes": "ඔව්",
    "No": "නැත",
    "TRI Circulars": "TRI චක්‍රලේඛ",
    "Official Tea Research Institute advisory registry": "නිල තේ පර්යේෂණ ආයතන උපදේශන ලේඛනය",
    "Distribute New Circular": "නව චක්‍රලේඛයක් බෙදාහරින්න",
    "Search circulars...": "චක්‍රලේඛ සොයන්න...",
    "CIRCULAR ID": "චක්‍රලේඛ හැඳුනුම්පත",
    "TITLE": "මාතෘකාව",
    "DATE": "දිනය",
    "DISTRIBUTED": "බෙදා හරින ලදි",
    "READ": "කියවන ලදි",
    "READ %": "කියවූ %",
    "ACTIONS": "ක්‍රියාමාර්ග",
    "View": "නරඹන්න",
    "Resend": "නැවත යවන්න",
    "All Types": "සියලුම වර්ග",
    "Advance": "අත්තිකාරම්",
    "Fertilizer": "පොහොර",
    "Transport": "ට්රාන්ස්පෝර්ට්",
    "Machine Rent": "යන්ත්‍රෝපකරණ කුලිය",
    "Tools": "මෙවලම්",
    "Advisory": "උපදේශන",
    "Leaf Bags": "දළු බෑග්",
    "Tool Purchase": "මෙවලම් මිලදී ගැනීම",
    "bags": "බෑග්",
    "days": "දින",
    "units": "ඒකක",
    "Soil query": "පස පිළිබඳ ගැටළුවක්",
    "Provision": "සැපයීම",
    "Request Detail": "ඉල්ලීම් විස්තර",
    "Advisory Request Info": "උපදේශන ඉල්ලීම් තොරතුරු",
    "Subject": "විෂය",
    "Amount / Qty": "ප්‍රමාණය / ගණන",
    "Assigned Agent": "පැවරූ නියෝජිතයා",
    "Not Assigned": "පවරා නැත",
    "Financial Standing": "මූල්‍ය තත්ත්වය",
    "Outstanding Debt": "ගෙවිය යුතු මුළු ණය",
    "Supply This Month": "මේ මාසයේ සැපයුම",
    "Debt/Supply Ratio": "ණය/සැපයුම් අනුපාතය",
    "Tip": "ඉඟිය",
    "Review debt ratio carefully": "ණය අනුපාතය ප්‍රවේශමෙන් පරීක්ෂා කරන්න",
    "Transport Service": "ට්රාන්ස්පෝර්ට් සේවය",
    "Standard Transport": "සාමාන්‍ය ට්රාන්ස්පෝර්ට්",
    "Service Category": "සේවා කාණ්ඩය",
    "Logistic": "ට්රාන්ස්පෝර්ට්",
    "Transport Fee (Rs.)": "ට්රාන්ස්පෝර්ට් ගාස්තුව (රු.)",
    "Rental Configuration": "කුලී සැකසුම",
    "Rental Machine": "කුලී යන්ත්‍රය",
    "Duration": "කාලසීමාව",
    "Days": "දින",
    "Total Rental Fee (Rs.)": "මුළු කුලී ගාස්තුව (රු.)",
    "Inventory Pricing": "තොග මිලකරණය",
    "unit": "ඒකකය",
    "Calculated Total": "ගණනය කළ එකතුව",
    "Source": "මූලාශ්‍රය",
    "Direct": "සෘජු",
    "Passbook": "පාස්බුක් නම්බර්",
    "Emp ID": "සේවක හැඳුනුම්පත",
    "Requested At": "ඉල්ලුම් කළ වේලාව",
    "Supplier Note": "සැපයුම්කරුගේ සටහන",
    "Agent Note": "නියෝජිතයාගේ සටහන",
    "Decision Status": "තීරණයේ තත්ත්වය",
    "Rejected At": "ප්‍රතික්ෂේප කළ වේලාව",
    "Approved At": "අනුමත කළ වේලාව",
    "APPROVED": "අනුමතයි",
    "APPROVED BY MGR": "කළමනාකරු විසින් අනුමත කරන ලදි",
    "REJECTED": "ප්‍රතික්ෂේපිතයි",
    "Extension Officer": "ව්‍යාප්ති නිලධාරී",
    "Factory Manager": "කර්මාන්තශාලා කළමනාකරු",
    "Administrator": "පරිපාලක",
    "Officer": "නිලධාරී",
    "Manager Remarks": "කළමනාකරුගේ අදහස්",
    "Final Deduction (Rs.)": "අවසාන අඩු කිරීම (රු.)",
    "Manager Remark": "කළමනාකරුගේ අදහස",
    "Add comment (optional)...": "අදහසක් එක් කරන්න (අත්‍යවශ්‍ය නොවේ)...",
    "Dismiss Request": "ඉල්ලීම ඉවත් කරන්න",
    "Reject Request": "ඉල්ලීම ප්‍රතික්ෂේප කරන්න",
    "Send Advice": "උපදෙස් යවන්න",
    "Approve & Send to Store Keeper": "අනුමත කර ස්ටොර් කීපර් වෙත යවන්න",
    "Approve Request": "ඉල්ලීම අනුමත කරන්න",
    "Confirm Dispatch": "බෙදා හැරීම තහවුරු කරන්න",
    "Ready to Dispatch": "බෙදා හැරීමට සූදානම්",
    "Dispatched Today": "අද බෙදා හරින ලදි",
    "Approved Today": "අද අනුමත කරන ලදි",
    "Rejected Today": "අද ප්‍රතික්ෂේප කරන ලදි",
    "Export List": "ලැයිස්තුව අපනයනය කරන්න",
    "Pending Approvals": "අනුමැතිය සඳහා රැඳී පවතින",
    "Dispatched": "බෙදා හරින ලද",
    "Recently Approved": "මෑතකදී අනුමත කළ",
    "Recently Rejected": "මෑතකදී ප්‍රතික්ෂේප කළ",
    "Search by name or ID...": "නම හෝ හැඳුනුම්පත අනුව සොයන්න...",
    "Request ID": "ඉල්ලීම් හැඳුනුම්පත",
    "Type": "වර්ගය",
    "Available": "තිබේ",
    "Debt": "ණය",
    "Status": "තත්ත්වය",
    "No requests found": "කිසිදු ඉල්ලීමක් හමු නොවීය",
    "Dispatch": "බෙදා හරින්න",
    "Approve": "අනුමත කරන්න",
    "Reject": "ප්‍රතික්ෂේප කරන්න",
    "Open to respond": "පිළිතුරු දීමට විවෘතයි",
    "Action failed.": "ක්‍රියාව අසාර්ථක විය.",
    "Financial Treasury": "මූල්‍ය භාණ්ඩාගාරය",
    "Manage supplier payouts, advances, and ledger reconciliation": "සැපයුම්කරුවන්ගේ ගෙවීම්, අත්තිකාරම් සහ ලෙජර සමගි කිරීම් කළමනාකරණය කරන්න",
    "Leaf Price: Rs.": "දළු මිල: රු.",
    "Syncing...": "සමමුහුර්ත වෙමින් පවතී...",
    "Sync Ledgers": "ලෙජර සමමුහුර්ත කරන්න",
    "Overview": "දළ විශ්ලේෂණය",
    "Payout Generator": "ගෙවීම් උත්පාදනය",
    "Supplier Ledgers": "සැපයුම්කරුවන්ගේ ලෙජර",
    "Treasury Settings": "භාණ්ඩාගාර සැකසුම්",
    "Projected Payout": "ප්‍රක්ෂේපිත ගෙවීම",
    "Unpaid net weight total": "නොගෙවූ මුළු ශුද්ධ බර",
    "Paid (Current Month)": "ගෙවන ලද (මේ මාසයේ)",
    "18 transactions completed": "ගනුදෙනු 18 ක් අවසන් කරන ලදි",
    "Active Advances": "සක්‍රිය අත්තිකාරම්",
    "Awaiting deduction": "අඩු කිරීමට නියමිත",
    "Debt Recovery": "ණය අයකර ගැනීම",
    "Outstanding store credits": "ගෙවිය යුතු ගබඩා ණය",
    "Recent Transactions": "මෑතකාලීන ගනුදෙනු",
    "Cash flow reconciliation": "මුදල් ප්‍රවාහ සමගි කිරීම",
    "View All": "සියල්ල නරඹන්න",
    "Payout": "ගෙවීම",
    "Cleared": "නිරවුල් කරන ලදි",
    "Treasury Snapshot": "භාණ්ඩාගාර දළ සටහන",
    "Available cash reserves for supplier settlements this cycle.": "මෙම චක්‍රයේ සැපයුම්කරුවන්ගේ පියවීම් සඳහා පවතින මුදල් සංචිත.",
    "Monthly Target": "මාසික ඉලක්කය",
    "Generate Balance Sheet": "ශේෂ පත්‍රය උත්පාදනය කරන්න",
    "Mass Payout Generator": "සමූහ ගෙවීම් උත්පාදනය",
    "Process earnings for all suppliers in a specific cycle": "නිශ්චිත චක්‍රයක සියලුම සැපයුම්කරුවන්ගේ ඉපැයීම් සකසන්න",
    "April 2026": "2026 අප්‍රේල්",
    "March 2026": "2026 මාර්තු",
    "February 2026": "2026 පෙබරවාරි",
    "Processing...": "සකසමින් පවතී...",
    "Run Calculations": "ගණනය කිරීම් සිදු කරන්න",
    "Gross Earnings": "දළ ඉපැයීම්",
    "Final Payout": "අවසාන ගෙවීම",
    "Search supplier by name or passbook...": "නම හෝ පාස්බුක් නම්බර් අනුව සැපයුම්කරු සොයන්න...",
    "Filters": "පෙරහන්",
    "Balance Owed": "ගෙවිය යුතු ශේෂය",
    "Last": "අවසන්",
    "Treasury Configuration": "භාණ්ඩාගාර වින්‍යාසය",
    "Global parameters for financial calculations": "මූල්‍ය ගණනය කිරීම් සඳහා ගෝලීය පරාමිතීන්",
    "Current Green Leaf Price (Rs/kg)": "වත්මන් අමු දළු මිල (රු/kg)",
    "This price will be used for all projected earnings and payout calculations.": "මෙම මිල සියලුම ප්‍රක්ෂේපිත ඉපැයීම් සහ ගෙවීම් ගණනය කිරීම් සඳහා භාවිතා කරනු ඇත.",
    "Issue": "නිකුත් කරන්න",
    "TOTAL FERTILIZER STOCK": "මුළු පොහොර තොගය",
    "Urea + TSP + MOP": "යූරියා + TSP + MOP",
    "TOTAL LEAF BAGS": "මුළු දළු බෑග් ගණන",
    "Standard + Large": "සාමාන්‍ය + විශාල",
    "LOW STOCK ALERTS": "අඩු තොග පිළිබඳ අනතුරු ඇඟවීම්",
    "Urea Fertilizer": "යූරියා පොහොර",
    "TOOLS UNITS": "මෙවලම් ඒකක",
    "1 reserved (TA-003)": "1 ක් වෙන් කර ඇත (TA-003)",
    "stock is below reorder level": "තොගය නැවත ඇණවුම් කිරීමේ මට්ටමට වඩා අඩුය",
    "remaining": "ඉතිරිව ඇත",
    "reorder at": "නැවත ඇණවුම් කිරීම",
    "Reorder Now": "දැන් නැවත ඇණවුම් කරන්න",
    "Inventory Items": "තොග අයිතමයන්",
    "Add Item": "අයිතමයක් එක් කරන්න",
    "Search item...": "අයිතමය සොයන්න...",
    "All Categories": "සියලුම වර්ග",
    "Bags": "බෑග්",
    "ITEM": "අයිතමය",
    "CATEGORY": "වර්ගය",
    "STOCK": "තොගය",
    "RESERVED": "වෙන් කර ඇති",
    "REORDER LEVEL": "නැවත ඇණවුම් කිරීමේ මට්ටම",
    "STOCK LEVEL": "තොග මට්ටම",
    "UNIT COST": "ඒකක පිරිවැය",
    "available": "තිබේ",
    "reserved": "වෙන් කර ඇත",
    "Low Stock": "අඩු තොග",
    "OK": "හොඳයි",
    "History": "ඉතිහාසය",
    "Update": "යාවත්කාලීන කරන්න",
    "Update Stock": "තොග යාවත්කාලීන කරන්න",
    "SELECTED ITEM": "තෝරාගත් අයිතමය",
    "New Stock": "නව තොගය",
    "Unit Cost": "ඒකක පිරිවැය",
    "Cancel": "අවලංගු කරන්න",
    "Saving...": "සුරැකෙමින් පවතී...",
    "Save Changes": "වෙනස්කම් සුරකින්න",
    "Failed to update item": "අයිතමය යාවත්කාලීන කිරීමට අපොහොසත් විය",
    "Dashboard": "පාලන පුවරුව",
    "Collections": "එකතු කිරීම්",
    "Financials": "මූල්‍ය කටයුතු",
    "Inventory": "තොග කළමනාකරණය",
    "Requests & Approvals": "ඉල්ලීම් සහ අනුමැතීන්",
    "Transport Tracking": "ට්රාන්ස්පෝර්ට් ලුහුබැඳීම",
    "Quality Assessment": "තත්ත්ව පරීක්ෂාව",
    "TRI Circulars": "TRI චක්‍රලේඛ",
    "Reports": "වාර්තා",
    "User Management": "පරිශීලක කළමනාකරණය",
    "Settings": "සැකසුම්",
    "Manager": "කළමනාකරු",
    "Extension Officer": "ව්‍යාප්ති නිලධාරී",
    "Office Staff": "කාර්යාල කාර්ය මණ්ඩලය",
    "Store Keeper": "ස්ටොර් කීපර්",
    "Factory Staff": "ෆැක්ටරි ස්ටාෆ්",
    "Sign Out": "පිටවෙන්න",
    "Next Payout Date": "මීළඟ ගෙවීම් දිනය",
    "This date will be applied to all pending suppliers for the current cycle.": "මෙම දිනය වත්මන් චක්‍රයේ සියලුම දළු සැපයුම්කරුවන් සඳහා අදාළ වේ.",
    "PAY": "ගෙවන්න",
    "PENDING": "ගෙවීමට නියමිතයි",
    "Balance Payments": "ශේෂ ගෙවීම්",
    "BALANCE PAYMENTS PENDING": "පොරොත්තු ශේෂ ගෙවීම්",
    "AWAITING APPROVAL": "අනුමැතිය අපේක්ෂාවෙන්",
    "TOTAL ADVANCES OUT": "මුළු නිකුත් කළ අත්තිකාරම්",
    "TOTAL DEBT PORTFOLIO": "මුළු ණය කළඹ",
    "PAYMENT ID": "ගෙවීම් හැඳුනුම්පත",
    "GROSS (RS.)": "දළ (රු.)",
    "ADVANCE DED.": "අත්තිකාරම් අඩු කිරීම්",
    "DEBT DED.": "ණය අඩු කිරීම්",
    "NET PAY": "ශුද්ධ ගෙවීම",
    "DUE/PAID": "නියමිත/ගෙවූ",
    "Export Excel": "එක්සෙල් අපනයනය",
    "suppliers": "සැපයුම්කරුවන්",
    "requests": "ඉල්ලීම්",
    "Current Cycle": "වත්මන් චක්‍රය",
    "All Holders": "සියලුම දරන්නන්",
    "Sign In": "ඇතුළු වන්න",
    "To Access The Portal": "පද්ධතියට පිවිසීමට",
    "Username or Email": "පරිශීලක නාමය හෝ විද්‍යුත් තැපෑල",
    "Password": "මුරපදය",
    "Enter username or email": "පරිශීලක නාමය හෝ විද්‍යුත් තැපෑල ඇතුළත් කරන්න",
    "Identify & Portal": "හඳුනාගෙන පිවිසෙන්න",
    "New estate establishment?": "නව වතුයායක් ලියාපදිංචි කිරීම?",
    "Register here": "මෙහි ලියාපදිංචි වන්න",
    "Strategic Support": "උපායමාර්ගික සහාය",
    "Onboarding": "ලියාපදිංචි කිරීම",
    "Phase": "අදියර",
    "of": "න්",
    "Official Estate Name": "නිල වතුයායේ නම",
    "e.g. Riverside Highlands": "උදා: රිවර්සයිඩ් හයිලන්ඩ්ස්",
    "Division Code": "අංශ කේතය",
    "Manager Full Name": "කළමනාකරුගේ සම්පූර්ණ නම",
    "Contact Phone": "සම්බන්ධතා දුරකථන අංකය",
    "Physical Address": "භෞතික ලිපිනය",
    "Location details": "ස්ථාන විස්තර",
    "Master Admin Email": "ප්‍රධාන පරිපාලක විද්‍යුත් තැපෑල",
    "Administrator Password": "පරිපාලක මුරපදය",
    "Confirm & Register": "තහවුරු කර ලියාපදිංචි වන්න",
    "Estate onboarded successfully! Access cleared for management.": "වතුයාය සාර්ථකව ලියාපදිංචි කරන ලදී! කළමනාකරණය සඳහා ප්‍රවේශය ලබා දී ඇත.",
    "Registration failed. Please check your connection.": "ලියාපදිංචිය අසාර්ථක විය. කරුණාකර ඔබේ සම්බන්ධතාවය පරීක්ෂා කරන්න.",
    "Passwords do not match.": "මුරපද නොගැලපේ.",
    "1. Estate Name": "1. වතුයායේ නම",
    "2. Manager Full Name": "2. කළමනාකරුගේ සම්පූර්ණ නම",
    "3. Contact Phone": "3. සම්බන්ධතා දුරකථන අංකය",
    "4. Physical Address": "4. භෞතික ලිපිනය",
    "5. Master Admin Email": "5. ප්‍රධාන පරිපාලක විද්‍යුත් තැපෑල",
    "6. Administrator Password": "6. පරිපාලක මුරපදය",
    "7. Confirm Password": "7. මුරපදය තහවුරු කරන්න"
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Language>(() => {
    return (localStorage.getItem('app_lang') as Language) || 'en';
  });

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem('app_lang', newLang);
  };

  const t = (key: string): string => {
    if (lang === 'si' && dictionary.si[key]) {
      return dictionary.si[key];
    }
    return key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
