import { StyleSheet } from "react-native";

export const palette = {
  bgOuter: "#040d20",
  bgInnerTop: "#1c2f4a",
  bgInnerBottom: "#08162f",
  muted: "#7f9cc5",
  white: "#eaf3ff",
  accentBlue: "#2ea8ff",
  accentGreen: "#1fbe57",
  input: "#04132b",
};

export const styles = StyleSheet.create({
  root: { flex: 1 },
  safe: { flex: 1 },
  scroll: { flex: 1, alignItems: "center", justifyContent: "center", padding: 20 },
  scrollCompact: { padding: 10 },
  brandBlock: { alignItems: "center", marginBottom: 20 },
  logoHalo: {
    width: 120, height: 120, borderRadius: 60,
    alignItems: "center", justifyContent: "center",
    overflow: "hidden",
  },
  logoHaloCompact: { width: 90, height: 90, borderRadius: 45 },
  logo: { width: "100%", height: "100%" },
  logoCompact: { borderRadius: 45 },
  brandSinhala: { color: "#fff", fontSize: 32, fontWeight: "bold", marginTop: 10 },
  brandSinhalaCompact: { fontSize: 26 },
  brandEn: { color: palette.muted, fontSize: 13, letterSpacing: 1 },
  brandEnCompact: { fontSize: 11 },
  authCard: {
    width: "100%", maxWidth: 420, backgroundColor: "rgba(16, 35, 66, 0.98)",
    borderRadius: 24, padding: 25, borderWidth: 1, borderColor: "rgba(255,255,255,0.06)",
  },
  authCardCompact: { padding: 15 },
  roleTabs: { flexDirection: "row", backgroundColor: "transparent", borderRadius: 20, padding: 4, marginBottom: 20, borderWidth: 1, borderColor: "#1b375d" },
  tab: { flex: 1, height: 42, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, borderRadius: 20 },
  tabActive: { backgroundColor: palette.accentBlue },
  tabText: { color: palette.muted, fontWeight: "600", fontSize: 14 },
  cardTitle: { color: "#fff", fontSize: 24, fontWeight: "bold" },
  cardTitleCompact: { fontSize: 20 },
  cardSubtitle: { color: palette.muted, fontSize: 13, marginBottom: 20, marginTop: 4 },
  label: { color: palette.muted, fontSize: 10, fontWeight: "bold", marginBottom: 8, letterSpacing: 1 },
  inputContainer: { 
    flexDirection: 'row', alignItems: 'center', 
    height: 48, backgroundColor: palette.input, borderRadius: 12,
    marginBottom: 15, borderWidth: 1, borderColor: "#1b375d"
  },
  inputField: { flex: 1, color: "#fff", paddingHorizontal: 15, height: "100%" },
  inputRightIcon: { paddingHorizontal: 12, height: "100%", justifyContent: "center" },
  primaryBtn: {
    height: 52, backgroundColor: palette.accentGreen, borderRadius: 12,
    alignItems: "center", justifyContent: "center", marginTop: 10,
  },
  primaryBtnCompact: { height: 48 },
  primaryBtnText: { color: "#111", fontSize: 16, fontWeight: "bold" },
  primaryBtnTextCompact: { fontSize: 14 },
  helpCenterWrap: { marginTop: 15, alignItems: "center" },
  helpCenterText: { color: palette.muted, fontSize: 12 },
  helpCenterLink: { color: "#fff", fontWeight: "bold" },
  otpInput: {
    height: 60, backgroundColor: palette.input, borderRadius: 12, color: "#fff",
    fontSize: 26, textAlign: "center", letterSpacing: 12, marginBottom: 25,
    borderWidth: 1, borderColor: "#1b375d", fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
  },
  cancelText: { textAlign: "center", color: palette.muted, fontWeight: "600", fontSize: 14 },
  footer: { color: "#34507c", fontSize: 11, marginTop: 20 },
  centered: { textAlign: "center" },
  
  // Dashboard Styles
  dashboardWrap: { flex: 1, backgroundColor: "#061224" },
  topBar: { flexDirection: "row", padding: 20, paddingTop: Platform.OS === 'android' ? 40 : 20, alignItems: "center", backgroundColor: "#111f38", borderBottomWidth: 1, borderBottomColor: "#1b3151" },
  avatar: { width: 45, height: 45, borderRadius: 12, backgroundColor: "#3a5bd9", alignItems: "center", justifyContent: "center" },
  summaryCard: {
    backgroundColor: "rgba(16, 35, 66, 0.9)", borderRadius: 20, padding: 25, 
    borderWidth: 1, borderColor: "rgba(255,255,255,0.08)", marginBottom: 25,
  },
  summaryTitle: { color: palette.muted, fontSize: 14, fontWeight: "600", marginBottom: 8 },
  summaryValue: { color: "#fff", fontSize: 32, fontWeight: "bold", letterSpacing: -0.5 },
  summaryDivider: { height: 1, backgroundColor: "rgba(255,255,255,0.1)", marginVertical: 15 },
  summarySubLabel: { color: palette.muted, fontSize: 12, marginBottom: 4 },
  summarySubValue: { color: "#fff", fontSize: 15, fontWeight: "bold" },
  sectionHeader: { color: "#fff", fontSize: 18, fontWeight: "bold", marginBottom: 15 },
  listItem: { 
    flexDirection: "row", alignItems: "center", backgroundColor: "#0d1b33", 
    padding: 15, borderRadius: 16, marginBottom: 12, borderWidth: 1, borderColor: "rgba(255,255,255,0.03)"
  },
  listIcon: { width: 44, height: 44, borderRadius: 12, backgroundColor: "rgba(31, 190, 87, 0.15)", alignItems: "center", justifyContent: "center", marginRight: 15 },
  progressBar: { height: 8, backgroundColor: "rgba(255,255,255,0.1)", borderRadius: 4, marginTop: 15, overflow: "hidden" },
  progressFill: { height: "100%", backgroundColor: palette.accentGreen, borderRadius: 4 },
  quickActions: { flexDirection: "row", gap: 12, marginBottom: 30 },
  actionBtn: { flex: 1, height: 90, backgroundColor: palette.accentBlue, borderRadius: 16, alignItems: "center", justifyContent: "center", padding: 10 },
  actionBtnSecondary: { flex: 1, height: 90, backgroundColor: "rgba(46, 168, 255, 0.1)", borderRadius: 16, borderWidth: 1, borderColor: "rgba(46, 168, 255, 0.3)", alignItems: "center", justifyContent: "center", padding: 10 },
  actionBtnText: { color: "#fff", fontSize: 14, fontWeight: "600", marginTop: 8 },
  statBox: { flex: 1, backgroundColor: "rgba(16, 35, 66, 0.6)", borderRadius: 16, padding: 12, borderWidth: 1, alignItems: "flex-start" },
  statBoxValue: { color: "#fff", fontSize: 22, fontWeight: "bold", marginVertical: 6 },
  statBoxLabel: { color: palette.muted, fontSize: 10, fontWeight: "bold", letterSpacing: 0.5 },
  statBoxSub: { color: palette.muted, fontSize: 10, marginTop: 4 },
  actionGrid: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", gap: 10, marginBottom: 25 },
  gridBtn: { width: "48%", height: 90, borderRadius: 16, alignItems: "center", justifyContent: "center" },
  gridBtnText: { color: "#fff", fontWeight: "600", marginTop: 8, fontSize: 14 },
  collectionItem: { flexDirection: "row", alignItems: "center", backgroundColor: "rgba(16, 35, 66, 0.6)", padding: 15, borderRadius: 16, marginBottom: 10, borderWidth: 1, borderColor: "#1b375d" },
  collectionAvatar: { width: 44, height: 44, borderRadius: 12, alignItems: "center", justifyContent: "center", marginRight: 12 },
  collectionAvatarText: { color: "#fff", fontWeight: "bold", fontSize: 18 },
  badgeLine: { flexDirection: "row", alignItems: "center", borderWidth: 1, borderColor: palette.muted, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6 },
  badgeText: { fontSize: 10, fontWeight: "bold" },
  
  // New Screens Styles
  headerBar: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", padding: 15, paddingHorizontal: 20 },
  headerTitle: { color: "#fff", fontSize: 18, fontWeight: "bold" },
  iconBtn: { padding: 8, backgroundColor: "rgba(255,255,255,0.05)", borderRadius: 12 },
  searchBox: { flexDirection: "row", alignItems: "center", backgroundColor: "rgba(16, 35, 66, 0.6)", borderRadius: 12, paddingHorizontal: 15, height: 48, marginBottom: 15, borderWidth: 1, borderColor: "rgba(255,255,255,0.05)" },
  searchInput: { flex: 1, color: "#fff", marginLeft: 10, height: "100%" },
  filterRow: { flexDirection: "row", gap: 10, marginBottom: 20 },
  filterChip: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, borderWidth: 1, borderColor: "#1b375d" },
  filterChipActive: { backgroundColor: "rgba(31,190,87,0.15)", borderColor: palette.accentGreen },
  filterChipText: { color: palette.muted, fontSize: 13, fontWeight: "600" },
  filterChipTextActive: { color: palette.accentGreen },
  
  collectionItemCard: { flexDirection: "row", alignItems: "center", backgroundColor: "#0b192c", padding: 15, borderRadius: 16, marginBottom: 12, borderWidth: 1, borderColor: "rgba(255,255,255,0.05)" },
  collectionAvatarCompact: { width: 40, height: 40, borderRadius: 10, alignItems: "center", justifyContent: "center", marginRight: 15 },
  cardItemTitle: { color: "#fff", fontSize: 16, fontWeight: "bold" },
  cardItemSub: { color: palette.muted, fontSize: 12, marginTop: 2 },
  cardWeight: { color: palette.accentGreen, fontSize: 18, fontWeight: "bold" },
  cardTime: { color: palette.muted, fontSize: 12, marginTop: 4 },

  requestTabs: { flexDirection: "row", backgroundColor: "#0b192c", borderRadius: 12, padding: 4, marginBottom: 20, borderWidth: 1, borderColor: "rgba(255,255,255,0.05)" },
  reqTab: { flex: 1, flexDirection: "row", height: 40, alignItems: "center", justifyContent: "center", gap: 8, borderRadius: 8 },
  reqTabActive: { backgroundColor: "rgba(46, 168, 255, 0.15)" },
  reqTabText: { color: palette.muted, fontWeight: "600", fontSize: 14 },
  reqTabTextActive: { color: palette.accentBlue },
  
  reqCard: { backgroundColor: "#0b192c", borderRadius: 16, padding: 20, marginBottom: 15, borderWidth: 1, borderColor: "rgba(255,255,255,0.05)" },
  statusBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 6 },
  statusBadgeText: { fontSize: 10, fontWeight: "bold", letterSpacing: 0.5 },
  reqCardLabel: { color: palette.muted, fontSize: 13 },
  reqCardValue: { color: "#fff", fontSize: 14, fontWeight: "600" },
  
  floatingBottom: { position: "absolute", bottom: 90, left: 20, right: 20 },
  newReqBtn: { flexDirection: "row", height: 50, backgroundColor: "#061224", borderRadius: 12, alignItems: "center", justifyContent: "center", gap: 8 },
  newReqBtnText: { color: "#fff", fontSize: 16, fontWeight: "bold" },
  warningBox: { flexDirection: "row", backgroundColor: "rgba(243, 156, 18, 0.1)", padding: 12, borderRadius: 8, marginTop: 10, alignItems: "center", gap: 8, borderWidth: 1, borderColor: "rgba(243, 156, 18, 0.3)" },
  warningText: { color: "#f39c12", fontSize: 12 },

  profileHeader: { alignItems: "center", marginBottom: 25 },
  profileAvatarBig: { width: 80, height: 80, borderRadius: 40, backgroundColor: palette.accentGreen, alignItems: "center", justifyContent: "center", marginBottom: 15 },
  profileAvatarBigText: { color: "#fff", fontSize: 32, fontWeight: "bold" },
  profileName: { color: "#fff", fontSize: 22, fontWeight: "bold" },
  profileRole: { color: palette.muted, fontSize: 14, marginTop: 4 },
  profileIdBadge: { backgroundColor: "rgba(46, 168, 255, 0.15)", paddingHorizontal: 12, paddingVertical: 4, borderRadius: 12, marginTop: 10, borderWidth: 1, borderColor: "rgba(46, 168, 255, 0.3)" },
  profileIdText: { color: palette.accentBlue, fontSize: 12, fontWeight: "bold" },
  
  profileStatsRow: { flexDirection: "row", marginBottom: 30 },
  profileStatBox: { flex: 1, backgroundColor: "#0b192c", borderRadius: 16, padding: 15, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "rgba(255,255,255,0.05)" },
  profileStatValue: { color: "#fff", fontSize: 20, fontWeight: "bold", marginBottom: 4 },
  profileStatLabel: { color: palette.muted, fontSize: 10, fontWeight: "bold", letterSpacing: 0.5 },

  settingItem: { flexDirection: "row", alignItems: "center", backgroundColor: "#0b192c", padding: 15, borderRadius: 16, borderWidth: 1, borderColor: "rgba(255,255,255,0.05)" },
  settingIconBg: { width: 40, height: 40, borderRadius: 10, alignItems: "center", justifyContent: "center", marginRight: 15 },
  settingItemTitle: { color: "#fff", fontSize: 15, fontWeight: "bold" },
  settingItemSub: { color: palette.muted, fontSize: 12, marginTop: 2 },

  // Supplier Screens Styles
  onlineBadge: { flexDirection: "row", alignItems: "center", borderWidth: 1, borderColor: palette.accentGreen, paddingHorizontal: 12, paddingVertical: 4, borderRadius: 12, backgroundColor: "rgba(31,190,87,0.1)" },
  onlineBadgeText: { color: palette.accentGreen, fontSize: 12, fontWeight: "bold", marginLeft: 4 },
  
  supCard: { flex: 1, backgroundColor: "rgba(16, 35, 66, 0.9)", borderRadius: 20, padding: 15, borderWidth: 1, borderColor: "rgba(255,255,255,0.05)", borderTopWidth: 4 },
  supCardIcon: { width: 36, height: 36, borderRadius: 10, alignItems: "center", justifyContent: "center", marginBottom: 15 },
  supCardLabel: { color: palette.muted, fontSize: 11, fontWeight: "bold", letterSpacing: 0.5, marginBottom: 5 },
  supCardValue: { color: "#fff", fontSize: 22, fontWeight: "bold", marginBottom: 5 },
  supCardSub: { color: palette.muted, fontSize: 12 },
  
  serviceCard: { flex: 1, backgroundColor: "#0b192c", borderRadius: 16, padding: 15, alignItems: "center", borderWidth: 1, borderColor: "rgba(255,255,255,0.05)" },
  serviceIcon: { width: 50, height: 50, borderRadius: 25, backgroundColor: "rgba(16, 35, 66, 0.8)", alignItems: "center", justifyContent: "center", marginBottom: 10, borderWidth: 1 },
  serviceTitle: { color: "#fff", fontSize: 13, fontWeight: "bold", marginBottom: 10 },
  serviceBadge: { flexDirection: "row", alignItems: "center", borderWidth: 1, borderColor: "rgba(255,255,255,0.1)", paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12 },
  serviceBadgeText: { color: palette.muted, fontSize: 10 },

  supplySummaryBox: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", backgroundColor: "rgba(16, 35, 66, 0.9)", borderRadius: 20, padding: 20, borderWidth: 1, borderColor: "rgba(255,255,255,0.05)", marginBottom: 20 },
  supplySummValue: { color: "#fff", fontSize: 24, fontWeight: "bold", marginBottom: 4 },
  supplySummUnit: { fontSize: 16, color: "#fff", fontWeight: "normal" },
  supplySummLabel: { color: palette.muted, fontSize: 11, fontWeight: "bold", letterSpacing: 0.5 },
  supSummDivider: { width: 1, height: 40, backgroundColor: "rgba(255,255,255,0.1)" },

  filterChipActiveSup: { backgroundColor: "transparent", borderColor: palette.accentBlue },
  filterChipTextActiveSup: { color: palette.accentBlue },

  supplyHistItem: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", backgroundColor: "#0b192c", padding: 20, borderRadius: 16, marginBottom: 12, borderWidth: 1, borderColor: "rgba(255,255,255,0.05)" },
  supHistDate: { color: "#fff", fontSize: 16, fontWeight: "bold", marginBottom: 4 },
  supHistSub: { color: palette.muted, fontSize: 13 },
  supHistGross: { color: palette.accentGreen, fontSize: 20, fontWeight: "bold", marginBottom: 4 },

  nextPayBox: { flexDirection: "row", alignItems: "center", backgroundColor: "rgba(16, 35, 66, 0.9)", padding: 20, borderRadius: 16, marginBottom: 20, borderWidth: 1, borderColor: "rgba(255,255,255,0.05)" },
  nextPayTitle: { color: "#fff", fontSize: 16, fontWeight: "bold", marginBottom: 4 },
  nextPaySub: { color: palette.muted, fontSize: 13 },
  
  paymentCard: { backgroundColor: "rgba(16, 35, 66, 0.9)", borderRadius: 20, padding: 20, marginBottom: 15, borderWidth: 1, borderColor: "rgba(255,255,255,0.05)" },
  payCardHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 20 },
  payCardTitle: { color: "#fff", fontSize: 18, fontWeight: "bold" },
  payCardId: { color: palette.muted, fontSize: 12, marginTop: 4 },
  statusBadgeGrey: { flexDirection: "row", alignItems: "center", borderWidth: 1, borderColor: "rgba(255,255,255,0.1)", paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12, backgroundColor: "rgba(255,255,255,0.05)" },
  statusBadgeTextGrey: { color: palette.muted, fontSize: 11, marginLeft: 4 },
  payRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 10 },
  payLabel: { color: palette.muted, fontSize: 14 },
  payVal: { color: "#fff", fontSize: 14, fontWeight: "bold" },
  payValRed: { color: "#ff6b6b", fontSize: 14, fontWeight: "bold" },
  payDivider: { height: 1, backgroundColor: "rgba(255,255,255,0.1)", marginVertical: 15 },
  payTotalLabel: { color: "#fff", fontSize: 16, fontWeight: "bold" },
  payTotalVal: { color: palette.accentGreen, fontSize: 18, fontWeight: "bold" },
  payFooterTextYellow: { color: "#f39c12", fontSize: 12, fontStyle: "italic", marginTop: 15 },
  payFooterTextDim: { color: palette.muted, fontSize: 12, fontStyle: "italic", marginTop: 15 },

  debtSummaryCard: { backgroundColor: "rgba(231,76,60,0.15)", borderRadius: 20, padding: 25, alignItems: "center", marginBottom: 20, borderWidth: 1, borderColor: "rgba(231,76,60,0.3)" },
  debtTitle: { color: "#fff", fontSize: 14, marginBottom: 10 },
  debtAmount: { color: "#ff8a8a", fontSize: 36, fontWeight: "bold", marginBottom: 8 },
  debtSubTitle: { color: "#fff", fontSize: 14 },

  infoBox: { flexDirection: "row", backgroundColor: "rgba(46, 168, 255, 0.1)", padding: 15, borderRadius: 12, marginBottom: 20, borderWidth: 1, borderColor: "rgba(46, 168, 255, 0.3)" },
  infoBoxTitle: { color: "#fff", fontSize: 14, fontWeight: "bold", marginBottom: 4 },
  infoBoxText: { color: palette.muted, fontSize: 13, lineHeight: 18 },

  debtItemRow: { flexDirection: "row", alignItems: "center", backgroundColor: "rgba(16, 35, 66, 0.9)", padding: 15, borderRadius: 16, marginBottom: 12, borderWidth: 1, borderColor: "rgba(255,255,255,0.05)" },
  debtIconBox: { width: 44, height: 44, borderRadius: 12, backgroundColor: "rgba(255,255,255,0.05)", alignItems: "center", justifyContent: "center", marginRight: 15 },
  debtItemTitle: { color: "#fff", fontSize: 16, fontWeight: "bold", marginBottom: 4 },
  debtItemDate: { color: palette.muted, fontSize: 12 },
  debtItemVal: { color: "#fff", fontSize: 16, fontWeight: "bold" },

  clarifyBox: { flexDirection: "row", backgroundColor: "rgba(31, 190, 87, 0.1)", padding: 15, borderRadius: 12, marginTop: 10, borderWidth: 1, borderColor: "rgba(31, 190, 87, 0.3)" },
  clarifyTitle: { color: palette.accentGreen, fontSize: 14, fontWeight: "bold", marginBottom: 4 },
  clarifyText: { color: "rgba(255,255,255,0.7)", fontSize: 13, lineHeight: 18 },

  supplierBadge: { flexDirection: "row", alignItems: "center", backgroundColor: "rgba(46, 168, 255, 0.15)", paddingHorizontal: 12, paddingVertical: 4, borderRadius: 12, marginTop: 10, borderWidth: 1, borderColor: "rgba(46, 168, 255, 0.3)" },
  supplierBadgeText: { color: palette.accentBlue, fontSize: 12, fontWeight: "bold", marginLeft: 4 },
  supProfileIdBadge: { backgroundColor: "rgba(255,255,255,0.05)", paddingHorizontal: 15, paddingVertical: 6, borderRadius: 12, marginTop: 15 },
  supProfileIdText: { color: palette.muted, fontSize: 12, letterSpacing: 0.5 },

  supDetailsBox: { backgroundColor: "rgba(16, 35, 66, 0.9)", borderRadius: 16, padding: 20, borderWidth: 1, borderColor: "rgba(255,255,255,0.05)", marginBottom: 15 },
  supDetailRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 15 },
  supDetailKey: { color: palette.muted, fontSize: 14 },
  supDetailVal: { color: "#fff", fontSize: 14, fontWeight: "500" }
});
